import { AppProps } from '../node_modules/next/app';
import Head from '../node_modules/next/head';
import '../styles/globals.css';

function MyApp({ Component, pageProps }: AppProps) {
  return  <>
      <Head>
        <title>MyTop - мой топ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />        
      </Head>
      <Component {...pageProps} />;
    </>;  
}

export default MyApp;
